package com.movieticket.app.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.EnumMap;
import java.util.Map;

@Entity
@Table(name = "shows")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Show {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "movie_id", nullable = false)
    private Movie movie;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "screen_id", nullable = false)
    private Screen screen;

    @Column(nullable = false)
    private LocalDateTime showDateTime;

    /**
     * Held as plain text, not H2's native ENUM type. Hibernate's default for a
     * string enum is a native ENUM whose value list is fixed at creation, and
     * ddl-auto=update never widens it - so adding a constant to {@link ShowStatus}
     * would break every existing database. See ShowStatusColumnPatch.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, columnDefinition = "varchar(20)")
    private ShowStatus status;

    /**
     * Groups the screenings generated by one recurring plan. Nullable - a
     * one-off show has no series, and existing rows keep a null on upgrade.
     */
    @Column(length = 36)
    private String seriesId;

    @ElementCollection
    @CollectionTable(name = "show_prices", joinColumns = @JoinColumn(name = "show_id"))
    @MapKeyColumn(name = "seat_type")
    @MapKeyEnumerated(EnumType.STRING)
    @Column(name = "price", nullable = false)
    @Builder.Default
    private Map<SeatType, BigDecimal> prices = new EnumMap<>(SeatType.class);
}
